export const LOADING_ORGANIZATION = "LOADING_ORGANIZATION";
export const SET_ALL_ORGANIZATIONS = "SET_ALL_ORGANIZATIONS";
export const REMOVE_ORGANIZATION = "REMOVE_ORGANIZATION";
export const ADD_ORGANIZATION = "ADD_ORGANIZATION";
export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION";
export const ERROR_ORGANIZATION = "ERROR_ORGANIZATION";
export const SET_DEFAULT_ORGANIZATION = "SET_DEFAULT_ORGANIZATION";
export const SET_STARTED_ORGANIZATION = "SET_STARTED_ORGANIZATION";
