export const LOADING_ORGANIZATION = "LOADING_ORGANIZATION";

export const GET_ORGANIZATIONS = "GET_ORGANIZATIONS";
export const REMOVE_ORGANIZATION = "REMOVE_ORGANIZATION";
export const ADD_ORGANIZATION = "ADD_ORGANIZATION";
export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION";
export const ERROR_ORGANIZATION = "ERROR_ORGANIZATION";
export const SET_ORGANIZATION = "SET_ORGANIZATION";
export const SET_WORKSPACES = "SET_WORKSPACES";
