/**
 * Faros
 * Resource for managing Faros workspaces
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mangirdas@judeikis.LT
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OidcClaimSource } from '../models/OidcClaimSource';
import { HttpFile } from '../http/http';

export class OidcIDToken {
    'accessTokenHash': string;
    'audience': Array<string>;
    'expiry': Date;
    'issuedAt': Date;
    'issuer': string;
    'nonce': string;
    'subject': string;
    'claims': string;
    'distributedClaims': { [key: string]: OidcClaimSource; };
    'sigAlgorithm': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessTokenHash",
            "baseName": "AccessTokenHash",
            "type": "string",
            "format": ""
        },
        {
            "name": "audience",
            "baseName": "Audience",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "expiry",
            "baseName": "Expiry",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "issuedAt",
            "baseName": "IssuedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "issuer",
            "baseName": "Issuer",
            "type": "string",
            "format": ""
        },
        {
            "name": "nonce",
            "baseName": "Nonce",
            "type": "string",
            "format": ""
        },
        {
            "name": "subject",
            "baseName": "Subject",
            "type": "string",
            "format": ""
        },
        {
            "name": "claims",
            "baseName": "claims",
            "type": "string",
            "format": ""
        },
        {
            "name": "distributedClaims",
            "baseName": "distributedClaims",
            "type": "{ [key: string]: OidcClaimSource; }",
            "format": ""
        },
        {
            "name": "sigAlgorithm",
            "baseName": "sigAlgorithm",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OidcIDToken.attributeTypeMap;
    }

    public constructor() {
    }
}

