/**
 * Faros
 * Resource for managing Faros workspaces
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mangirdas@judeikis.LT
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1ObjectReference } from '../models/V1ObjectReference';
import { HttpFile } from '../http/http';

export class V1alpha1WorkspaceSpec {
    'description'?: string;
    'organizationRef'?: V1ObjectReference;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationRef",
            "baseName": "organizationRef",
            "type": "V1ObjectReference",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1WorkspaceSpec.attributeTypeMap;
    }

    public constructor() {
    }
}

